[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"  # Max compatibility - still support TSTORE, MCOPY and PUSH0.
optimizer = true
optimizer_runs = 10_000
via_ir = true
ignored_error_codes = [6335, 2424, 2394, 4591]
extra_output = ["ir", "irOptimized"]
extra_output_files = ["ir", "irOptimized"]
sizes = true
gas_reports = ['*']
remappings = [
    "@SafeSwap=src/",
    "@BondRoute=lib/BondRoute/src/",
    "@BondRouteProtected=lib/BondRoute/src/integrations/",
    "@ChainConfig=lib/ChainConfig/src/integrations/",
    "@openzeppelin/contracts/=lib/BondRoute/lib/openzeppelin-contracts/contracts/",
    "@UniswapV4Core=lib/v4-core/src/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@OpenZeppelin=lib/openzeppelin-contracts/contracts/",
    "@test=test/",
]

fs_permissions = [{ access = "read", path = "./out" }]

[invariant]
runs = 32
depth = 64

[lint]
exclude_lints = [
    "mixed-case-variable",
    "mixed-case-function",
    "screaming-snake-case-const",
    "screaming-snake-case-immutable",
    "unaliased-plain-import",
    "unsafe-typecast"
]
